### ISSUE TITLE
tardis failures

### ISSUE THREAD

**Issue by esc** [numba/numba-integration-testing#71]
Tardis began to fail 1 day ago, here is the log:

https://app.circleci.com/pipelines/github/numba/numba-integration-testing/735/workflows/47d9a844-342a-426f-a5d0-e0aec0d9a795/jobs/7601

@KevinCawley would you have a spare minute to take a look?

**Comment by KevinCawley** [comment]
Yes I am going to look into what package caused it. It's not TARDIS as our last release was 5 days ago, not yesterday.

**Comment by esc** [comment]
@KevinCawley awesome, thank you!

**Comment by KevinCawley** [comment]
I will wait to see if the new release of TARDIS will help resolve these changes, as there have been some updates to TARDIS refdata recently. The new release will happen tomorrow.

**Comment by esc** [comment]
@KevinCawley awesome!

**Comment by KevinCawley** [comment]
Hopefully this will be resolved this midnight.

**Comment by esc** [comment]
@KevinCawley fix looks good, `tardis`  was green this morning! 🎉

**Comment by esc** [comment]
Here is the run:

https://app.circleci.com/pipelines/github/numba/numba-integration-testing/742/workflows/03617d14-84f9-46f0-a28a-c551237d7f90/jobs/7667

And here is a screenshot of the last lines of the log, which indicate the Numba, llvmlite and tardis version.

<img width="847" alt="Screen Shot 2021-06-15 at 18 16 52" src="https://user-images.githubusercontent.com/41563/122088275-de059c00-ce05-11eb-82e0-683c6061974e.png">

**Comment by esc** [comment]
@KevinCawley looking at the following tag, this seems to be a different version than what was install (or reported?) above? 

https://github.com/tardis-sn/tardis/releases/tag/v3.0.dev3998

**Comment by KevinCawley** [comment]
It has always been that. I think that it may be the way that texasbbq formats the output for the version. As all of them have always been 3.0.dev1.

**Comment by esc** [comment]
I took another look at the log of the circleci task and this is the clone command that is being issued:
```
::>> running: 'git clone -b v3.0.dev3998 https://github.com/tardis-sn/tardis.git --depth=1 tardis'
```
